services:
  traefik:
    image: "traefik:v2.10.1"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - okpoykus
    depends_on:
      - astro
      - django

  astro:
    build: ./astro
    command: yarn start --host --port 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`astro.localhost`) && !PathPrefix(`/health`)"
      - "traefik.http.routers.astro.entrypoints=web"
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PUBLIC_LANGUAGE: ${ASTRO_LANGUAGE}
      PUBLIC_PORT: ${ASTRO_PORT}
      API_URL: django
      API_PORT: 8000
    volumes:
      - "./astro:/app:rw"
    networks:
      - okpoykus
    depends_on:
      - django

  django:
    build: ./django
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`astro.localhost`) && (PathPrefix(`/admin`)||PathPrefix(`/static`)||PathPrefix(`/media`)||PathPrefix(`/api`))"
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      PORT: ${PORT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file: .env
    volumes:
      - "./django:/app:rw"
    networks:
      - okpoykus
    depends_on:
      - db

  db:
    image: postgres:13.16-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - okpoykus

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     discovery.type: single-node
  #     xpack.security.enabled: "false"
  #     cluster.routing.allocation.disk.watermark.low: "97%"
  #     cluster.routing.allocation.disk.watermark.high: "98%"
  #     cluster.routing.allocation.disk.watermark.flood_stage: "99%"
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   networks:
  #     - okpoykus

volumes:
  pgdata:
  # esdata:

networks:
  okpoykus:
    driver: bridge