# Generated by Django 5.1.2 on 2024-10-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpgame',
            options={'ordering': ['-updated_at', 'name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.CreateModel(
            name='okpForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': [models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='games.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': [models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
    ]
