# Generated by Django 5.1.2 on 2024-11-03 20:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='core_head_highlight_bg',
            field=colorfield.fields.ColorField(default='#505f65', image_field=None, max_length=25, samples=None, verbose_name='Core Head Highlight Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_head_highlight_text',
            field=colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=25, samples=None, verbose_name='Core Head Highlight Text Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_head_mask_bg',
            field=colorfield.fields.ColorField(default='#51636b', image_field=None, max_length=25, samples=None, verbose_name='Core Head Mask Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_head_mask_text',
            field=colorfield.fields.ColorField(default='#a2acaf', image_field=None, max_length=25, samples=None, verbose_name='Core Head Mask Text Colour'),
        ),
    ]
