# Generated by Django 5.1.2 on 2024-11-05 04:06

import okp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpcharacter',
            name='avatar',
            field=okp.fields.okpImageField(blank=True, null=True, upload_to='characters/avatars', validators=[okp.fields.okpImageSizeValidator], verbose_name='Avatar'),
        ),
    ]
