# Generated by Django 5.1.3 on 2024-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_okpgame_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='is_abbr_auto',
            field=models.BooleanField(default=True, verbose_name='Auto-Generate Abbreviation'),
        ),
        migrations.AlterField(
            model_name='okpgame',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
