# Generated by Django 5.0.7 on 2024-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpgames', '0002_okpgame_created_at_okpgame_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
