# Generated by Django 5.1.3 on 2024-12-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_okpgame_is_abbr_auto_alter_okpgame_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okpgame',
            name='is_private',
        ),
        migrations.AddField(
            model_name='okpgame',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
    ]
