# Generated by Django 5.0.7 on 2024-08-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okpgames', '0004_okpgamecharacter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpgame',
            options={'ordering': ['name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
    ]
