# Generated by Django 5.1.2 on 2024-10-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_okpforumcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okpforumtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='okpforummessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='okpforumsection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='okpforummessage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='okpforummessage',
            name='section',
        ),
        migrations.RemoveField(
            model_name='okpforummessage',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='okpforumsection',
            name='game',
        ),
        migrations.RemoveField(
            model_name='okpforumtopic',
            name='section',
        ),
        migrations.RemoveField(
            model_name='okpforumtopic',
            name='game',
        ),
        migrations.DeleteModel(
            name='okpForumCategory',
        ),
        migrations.DeleteModel(
            name='okpForumMessage',
        ),
        migrations.DeleteModel(
            name='okpForumSection',
        ),
        migrations.DeleteModel(
            name='okpForumTopic',
        ),
    ]
