# Generated by Django 5.1.2 on 2024-10-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_okpforumtopic_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='version',
            field=models.CharField(default='0.1.0', verbose_name='Version'),
        ),
    ]
