# Generated by Django 5.1.2 on 2024-10-29 00:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_okpgametheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_sideleft_highlight_bg',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Hightlight Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_sideleft_highlight_text',
            field=colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Hightlight Text Colour'),
        ),
    ]
