# Generated by Django 5.1.2 on 2024-10-30 02:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_okpgametheme_core_sideleft_highlight_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='topic_title_hover',
            field=colorfield.fields.ColorField(default='#d3b018', image_field=None, max_length=25, samples=None, verbose_name='Topic Title Text Hover Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='topic_title_text',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Topic Title Text Colour'),
        ),
    ]
