# Generated by Django 5.1.2 on 2024-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_okpforummessage_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumcategory',
            name='sortby',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='sortby',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sort'),
        ),
    ]
