# Generated by Django 5.1.6 on 2025-03-18 00:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okp_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkpForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the forum is active and can be used.', verbose_name='Is Active')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the forum is visible to users.', verbose_name='Is Visible')),
                ('total_posts', models.IntegerField(default=0, verbose_name='Total Posts')),
                ('total_topics', models.IntegerField(default=0, verbose_name='Total Topics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum', to='okp_game.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['title', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OkpForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the category is visible to users.', verbose_name='Is Visible')),
                ('total_posts', models.IntegerField(default=0, verbose_name='Total Posts')),
                ('total_topics', models.IntegerField(default=0, verbose_name='Total Topics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='okp_forum.okpforum', verbose_name='Forum')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='okp_game.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['forum', models.OrderBy(models.F('order'), nulls_last=True), 'title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OkpForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the message is visible to users.', verbose_name='Is Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='okp_forum.okpforumcategory', verbose_name='Category')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='okp_game.okpgamecharacter', verbose_name='Character')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='okp_forum.okpforum', verbose_name='Forum')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='okp_game.okpgame', verbose_name='Game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='okpforumcategory',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_category', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.AddField(
            model_name='okpforum',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_forum', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.CreateModel(
            name='OkpForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('flex', models.PositiveSmallIntegerField(default=50, help_text='The percentage of the width of the section in index and category pages.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Flex')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the section is visible to users.', verbose_name='Is Visible')),
                ('total_posts', models.IntegerField(default=0, verbose_name='Total Posts')),
                ('total_topics', models.IntegerField(default=0, verbose_name='Total Topics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='okp_forum.okpforumcategory', verbose_name='Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='okp_forum.okpforum', verbose_name='Forum')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='okp_game.okpgame', verbose_name='Game')),
                ('last_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_section', to='okp_forum.okpforumpost', verbose_name='Last Post')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['forum', 'category', models.OrderBy(models.F('order'), nulls_last=True), 'title', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='okpforumpost',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='okp_forum.okpforumsection', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='OkpForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the topic is visible to users.', verbose_name='Is Visible')),
                ('total_posts', models.PositiveIntegerField(default=0, help_text='The total number of posts in the topic.', verbose_name='Total Posts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_forum.okpforumcategory', verbose_name='Category')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_game.okpgamecharacter', verbose_name='Character')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='okp_forum.okpforum', verbose_name='Forum')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='okp_game.okpgame', verbose_name='Game')),
                ('last_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_topic', to='okp_forum.okpforumpost', verbose_name='Last Post')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_forum.okpforumsection', verbose_name='Section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-last_post__updated_at', '-last_post__created_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='okpforumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='okp_forum.okpforumtopic', verbose_name='Topic'),
        ),
        migrations.AddConstraint(
            model_name='okpforumcategory',
            constraint=models.UniqueConstraint(fields=('forum', 'slug'), name='unique_category_slug_per_forum'),
        ),
        migrations.AddIndex(
            model_name='okpforumpost',
            index=models.Index(fields=['-created_at'], name='okp_forum_o_created_34640e_idx'),
        ),
        migrations.AddIndex(
            model_name='okpforumpost',
            index=models.Index(fields=['topic', 'is_visible', '-created_at'], name='okp_forum_o_topic_i_038889_idx'),
        ),
    ]
