# Generated by Django 5.1.6 on 2025-03-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0001_initial'),
        ('okp_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumpost',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='okp_game.okpgamecharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='okpforumpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='total_posts',
            field=models.PositiveIntegerField(default=0, help_text='The total number of posts in the topic.', verbose_name='Total Posts'),
        ),
        migrations.AlterField(
            model_name='okpforumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AddIndex(
            model_name='okpforumpost',
            index=models.Index(fields=['-created_at'], name='okp_forum_o_created_34640e_idx'),
        ),
        migrations.AddIndex(
            model_name='okpforumpost',
            index=models.Index(fields=['topic', 'is_visible', '-created_at'], name='okp_forum_o_topic_i_038889_idx'),
        ),
    ]
