# Generated by Django 5.1.6 on 2025-03-15 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforum',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_forum', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.AddField(
            model_name='okpforum',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
        migrations.AddField(
            model_name='okpforum',
            name='topic_count',
            field=models.IntegerField(default=0, verbose_name='Topic Count'),
        ),
    ]
