# Generated by Django 5.1.6 on 2025-03-18 03:41

import colorfield.fields
import django.core.validators
import okp.core.fields
import okp.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='cover',
            field=okp.core.fields.OkpImageField(blank=True, null=True, upload_to='forum/sections/cover', validators=[okp.core.validators.okp_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Cover'),
        ),
    ]
