# Generated by Django 5.1.6 on 2025-03-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
    ]
