# Generated by Django 5.1.6 on 2025-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0002_alter_okpforumtopic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforum',
            name='total_characters',
            field=models.IntegerField(default=0, verbose_name='Total Characters'),
        ),
        migrations.AddField(
            model_name='okpforum',
            name='total_users',
            field=models.IntegerField(default=0, verbose_name='Total Users'),
        ),
    ]
