# Generated by Django 5.1.6 on 2025-03-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0002_okpforum_last_post_okpforum_post_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okpforum',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='okpforum',
            name='topic_count',
        ),
        migrations.AddField(
            model_name='okpforum',
            name='total_posts',
            field=models.IntegerField(default=0, verbose_name='Total Posts'),
        ),
        migrations.AddField(
            model_name='okpforum',
            name='total_topics',
            field=models.IntegerField(default=0, verbose_name='Total Topics'),
        ),
        migrations.AddField(
            model_name='okpforumcategory',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_category', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.AddField(
            model_name='okpforumcategory',
            name='total_posts',
            field=models.IntegerField(default=0, verbose_name='Total Posts'),
        ),
        migrations.AddField(
            model_name='okpforumcategory',
            name='total_topics',
            field=models.IntegerField(default=0, verbose_name='Total Topics'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_section', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='total_posts',
            field=models.IntegerField(default=0, verbose_name='Total Posts'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='total_topics',
            field=models.IntegerField(default=0, verbose_name='Total Topics'),
        ),
    ]
