# Generated by Django 5.1.6 on 2025-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0002_okpforumsection_colour_okpforumsection_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='is_show_last_post',
            field=models.BooleanField(default=True, help_text='Whether to show the last post of the section in index and category pages.', verbose_name='Show Last Post'),
        ),
    ]
