# Generated by Django 5.1.6 on 2025-03-16 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0003_remove_okpforum_post_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'title', '-updated_at', '-created_at'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='flex',
            field=models.PositiveSmallIntegerField(default=50, help_text='The percentage of the width of the section in index and category pages.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Flex'),
        ),
    ]
