# Generated by Django 5.1.6 on 2025-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0003_okpforumsection_is_show_last_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumtopic',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the topic is locked and cannot be replied to.', verbose_name='Is Locked'),
        ),
    ]
