# Generated by Django 5.1.6 on 2025-03-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0004_alter_okpforumsection_options_okpforumsection_flex'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumtopic',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_topic', to='okp_forum.okpforumpost', verbose_name='Last Post'),
        ),
        migrations.AlterField(
            model_name='okpforumcategory',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
