# Generated by Django 5.1.6 on 2025-03-16 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forum', '0005_okpforumtopic_last_post_alter_okpforumcategory_order_and_more'),
        ('okp_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumcategory',
            options={'ordering': ['forum', models.OrderBy(models.F('order'), nulls_last=True), 'title', '-created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'ordering': ['forum', 'category', models.OrderBy(models.F('order'), nulls_last=True), 'title', '-created_at'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='okpforumtopic',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_game.okpgamecharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
