# Generated by Django 5.1.2 on 2024-10-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_okpgame_options_okpforumcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug'),
        ),
    ]
