# Generated by Django 5.1.2 on 2024-10-28 01:42

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_okpgame_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='okpGameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('core_primary', colorfield.fields.ColorField(default='#d3b018', image_field=None, max_length=25, samples=None, verbose_name='Default Primary Colour')),
                ('core_bg', colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=25, samples=None, verbose_name='Default Background Colour')),
                ('core_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Default Text Colour')),
                ('core_head_bg', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Core Head Background Colour')),
                ('core_head_text', colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=25, samples=None, verbose_name='Core Head Text Colour')),
                ('core_sideleft_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Background Colour')),
                ('core_sideleft_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Text Colour')),
                ('core_sideleft_mask_bg', colorfield.fields.ColorField(default='#869195', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Mask Background Colour')),
                ('core_sideleft_mask_text', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Mask Text Colour')),
                ('core_sideleft_highlight_bg', colorfield.fields.ColorField(default='#edf3f6', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Hightlight Background Colour')),
                ('core_sideleft_highlight_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Core Sideleft Hightlight Text Colour')),
                ('core_siderigh_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Core Siderigh Background Colour')),
                ('core_siderigh_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Core Siderigh Text Colour')),
                ('header_title', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Title Colour')),
                ('header_subtitle', colorfield.fields.ColorField(default='#869195', image_field=None, max_length=25, samples=None, verbose_name='Subtitle Colour')),
                ('header_separator', colorfield.fields.ColorField(default='#869195', image_field=None, max_length=25, samples=None, verbose_name='Separator Colour')),
                ('card_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Card Background Colour')),
                ('card_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Card Text Colour')),
                ('card_subtle', colorfield.fields.ColorField(default='#869195', image_field=None, max_length=25, samples=None, verbose_name='Card Subtle Text Colour')),
                ('card_mask_bg', colorfield.fields.ColorField(default='#869195', image_field=None, max_length=25, samples=None, verbose_name='Card Mask Background Colour')),
                ('card_mask_text', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Card Mask Text Colour')),
                ('card_radius', models.PositiveSmallIntegerField(default=4, verbose_name='Card Radius')),
                ('btn_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Button Background Colour')),
                ('btn_text', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Button Text Colour')),
                ('btn_primary_bg', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=25, samples=None, verbose_name='Button Primary Background Colour')),
                ('btn_primary_text', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=25, samples=None, verbose_name='Button Primary Text Colour')),
                ('btn_radius', models.PositiveSmallIntegerField(default=4, verbose_name='Button Radius')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': [models.OrderBy(models.F('game'), nulls_last=True), '-updated_at'],
            },
        ),
    ]
