# Generated by Django 5.1.6 on 2025-03-18 00:15

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import okp.core.fields
import okp.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkpGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('abbr', models.CharField(blank=True, max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Abbreviation')),
                ('founder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Founder')),
                ('founder_link', models.URLField(blank=True, null=True, verbose_name='Founder Link')),
                ('founded_at', models.DateField(blank=True, null=True, verbose_name='Founded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['title', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OkpGameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('abbr', models.CharField(blank=True, max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Abbreviation')),
                ('avatar', okp.core.fields.OkpImageField(blank=True, null=True, upload_to='characters/avatars', validators=[okp.core.validators.okp_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the character is active and can be used.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='okp_game.okpgame', verbose_name='Game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OkpGameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, help_text='If the theme is active, it will be used for the game.', verbose_name='Is Active')),
                ('primary', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Primary Colour')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='okp_game.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Game Theme',
                'verbose_name_plural': 'Game Themes',
                'ordering': ['name'],
            },
        ),
    ]
