# Generated by Django 5.1.6 on 2025-03-14 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkpGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('abbr', models.CharField(blank=True, max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Abbreviation')),
                ('founder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Founder')),
                ('founder_link', models.URLField(blank=True, null=True, verbose_name='Founder Link')),
                ('founded_at', models.DateField(blank=True, null=True, verbose_name='Founded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['title', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OkpGameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Slug')),
                ('abbr', models.CharField(blank=True, max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Auto-Generate Abbreviation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the character is active and can be used.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='okp_game.okpgame', verbose_name='Game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name', '-updated_at', '-created_at'],
            },
        ),
    ]
