# Generated by Django 5.1.6 on 2025-03-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the game is active and can be used.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='okpgame',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the game is public and can be viewed by everyone.', verbose_name='Is Public'),
        ),
    ]
