# Generated by Django 5.1.6 on 2025-03-17 21:06

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkpGameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, help_text='If the theme is active, it will be used for the game.', verbose_name='Is Active')),
                ('primary', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Primary Colour')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='okp_game.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Game Theme',
                'verbose_name_plural': 'Game Themes',
                'ordering': ['name'],
            },
        ),
    ]
