# Generated by Django 5.1.6 on 2025-03-26 14:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0002_okpgame_is_active_okpgame_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='card_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Card Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='card_placeholder_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Card Placeholder Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_elevated_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Elevated Background Colour'),
        ),
        migrations.AddField(
            model_name='okpgametheme',
            name='core_header_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Header Background Colour'),
        ),
    ]
