# Generated by Django 5.1.6 on 2025-03-26 14:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0003_okpgametheme_card_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='core_fg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Text Colour'),
        ),
    ]
