# Generated by Django 5.1.6 on 2025-03-26 14:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0004_okpgametheme_core_fg'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='core_header_fg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Header Text Colour'),
        ),
    ]
