# Generated by Django 5.1.6 on 2025-03-26 15:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0006_okpgametheme_card_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='card_placeholder_fg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Card Placeholder Text Colour'),
        ),
    ]
