# Generated by Django 5.1.6 on 2025-03-26 15:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0008_okpgametheme_core_elevated_fg'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='core_border',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Core Border Colour'),
        ),
    ]
