# Generated by Django 5.1.6 on 2025-03-27 00:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0010_okpgametheme_core_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpgametheme',
            name='card_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Card Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='card_placeholder_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Card Placeholder Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='card_placeholder_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Card Placeholder Text Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='card_separator',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Card Separator Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_border',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Border Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_elevated_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Elevated Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_elevated_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Elevated Text Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Text Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_header_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Header Background Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_header_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Header Text Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='core_link',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Link Colour'),
        ),
        migrations.AlterField(
            model_name='okpgametheme',
            name='primary',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Primary Colour'),
        ),
    ]
