# Generated by Django 5.1.6 on 2025-03-29 14:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0012_okpgamecharacter_last_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgametheme',
            name='core_subtle_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Core Subtle Text Colour'),
        ),
    ]
