# Generated by Django 5.1.6 on 2025-03-29 14:19

import django.core.validators
import okp.core.fields
import okp.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0013_okpgametheme_core_subtle_fg'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='cover',
            field=okp.core.fields.OkpImageField(blank=True, null=True, upload_to='games/covers', validators=[okp.core.validators.okp_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='okpgame',
            name='logo',
            field=okp.core.fields.OkpImageField(blank=True, null=True, upload_to='games/logos', validators=[okp.core.validators.okp_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='okpgame',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
