# Generated by Django 5.1.6 on 2025-03-29 14:41

import okp.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0014_okpgame_cover_okpgame_logo_okpgame_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpgame',
            name='favicon',
            field=okp.core.fields.OkpImageField(blank=True, null=True, upload_to='games/favicons', verbose_name='Favicon'),
        ),
    ]
