# Generated by Django 5.1.7 on 2025-04-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_game', '0015_okpgame_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpgame',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the game is public and can be viewed by everyone.', verbose_name='Is Public'),
        ),
    ]
