# Generated by Django 5.1.7 on 2025-04-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_auth', '0002_okpuser_last_post_okpuser_total_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpuser',
            name='max_owned_games',
            field=models.IntegerField(default=2, help_text='The maximum number of games a user can own.', verbose_name='Max Owned Games'),
        ),
    ]
