# Generated by Django 5.1.2 on 2024-11-05 00:57

import django.db.models.deletion
import okp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okp_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='okpForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='okp_games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['game', models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okp_forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okp_games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('banner', okp.fields.okpImageField(blank=True, null=True, upload_to='forums/sections/banners', validators=[okp.fields.okpImageSizeValidator], verbose_name='Banner')),
                ('banner_height', models.PositiveSmallIntegerField(default=100, verbose_name='Banner Height')),
                ('basis', models.CharField(choices=[('100', '100% (4/4)'), ('75', '75% (3/4)'), ('66', '66% (2/3)'), ('50', '50% (2/4)'), ('33', '33% (1/3)'), ('25', '25% (1/4)')], default='25', max_length=4, verbose_name='Basis')),
                ('total_topics', models.PositiveSmallIntegerField(default=0, verbose_name='Total Topics')),
                ('total_messages', models.PositiveSmallIntegerField(default=0, verbose_name='Total Messages')),
                ('show_last_message', models.BooleanField(default=True, verbose_name='Show Last Message')),
                ('show_last_topic', models.BooleanField(default=True, verbose_name='Show Last Topic')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='okp_forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='okp_games.okpgame', verbose_name='Game')),
                ('last_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_section', to='okp_forums.okpforummessage', verbose_name='Last Message')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['game', 'category', models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='okpforummessage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okp_forums.okpforumsection', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='okpForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('total_messages', models.PositiveSmallIntegerField(default=0, verbose_name='Total Messages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_games.okpgame', verbose_name='Game')),
                ('last_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_topic', to='okp_forums.okpforummessage', verbose_name='Last Message')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okp_forums.okpforumsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='last_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_topic_section', to='okp_forums.okpforumtopic', verbose_name='Last Topic'),
        ),
        migrations.AddField(
            model_name='okpforummessage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okp_forums.okpforumtopic', verbose_name='Topic'),
        ),
    ]
