# Generated by Django 5.1.2 on 2024-10-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_remove_okpforumtopic_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='okpForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Forum: Categories',
                'ordering': [models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('sortby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='games.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Forum: Sections',
                'ordering': [models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='games.okpgame', verbose_name='Game')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='forums.okpforumsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Forum: Topics',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='okpForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forums.okpforumcategory', verbose_name='Category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='games.okpgame', verbose_name='Game')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forums.okpforumsection', verbose_name='Category')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forums.okpforumtopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Forum: Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
