# Generated by Django 5.0.7 on 2024-07-11 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okpgames', '0002_okpgame_created_at_okpgame_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='okpForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='okpgames.okpgame', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='okpForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Name')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('list_topics', models.JSONField(verbose_name='List of Topics')),
                ('total_topics', models.PositiveSmallIntegerField(verbose_name='Total Topics')),
                ('total_messages', models.PositiveIntegerField(verbose_name='Total Messages')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='okpforums.okpforum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='okpForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Name')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('list_topics', models.JSONField(verbose_name='List of Topics')),
                ('total_topics', models.PositiveSmallIntegerField(verbose_name='Total Topics')),
                ('total_messages', models.PositiveIntegerField(verbose_name='Total Messages')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='okpforums.okpforumcategory', verbose_name='Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='okpforums.okpforum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='okpForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('total_messages', models.PositiveIntegerField(verbose_name='Total Messages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okpforums.okpforumcategory', verbose_name='Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='okpforums.okpforum', verbose_name='Forum')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='okpforums.okpforumsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='okpForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okpforums.okpforumcategory', verbose_name='Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='okpforums.okpforum', verbose_name='Forum')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='okpforums.okpforumsection', verbose_name='Section')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='okpforums.okpforumtopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
    ]
