# Generated by Django 5.1.2 on 2024-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumsection',
            name='basis',
            field=models.CharField(choices=[('auto', 'Default'), ('25', '25% (1/4)'), ('33', '33% (1/3)'), ('50', '50% (2/4)'), ('66', '66% (2/3)'), ('75', '75% (3/4)'), ('100', '100% (4/4)')], default='auto', max_length=4, verbose_name='Basis'),
        ),
    ]
