# Generated by Django 5.1.2 on 2024-11-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='show_last_message',
            field=models.BooleanField(default=True, verbose_name='Show Last Message'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='show_last_topic',
            field=models.BooleanField(default=True, verbose_name='Show Last Topic'),
        ),
    ]
