# Generated by Django 5.0.7 on 2024-07-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='okpforumcategory',
            name='list_topics',
            field=models.JSONField(default=list, verbose_name='List of Topics'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='list_topics',
            field=models.JSONField(default=list, verbose_name='List of Topics'),
        ),
    ]
