# Generated by Django 5.1.2 on 2024-11-06 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0002_alter_okpforumsection_basis'),
        ('okp_games', '0002_okpcharacter_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforummessage',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_messages', to='okp_games.okpcharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='okpforummessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_topics', to='okp_games.okpcharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_topics', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
