# Generated by Django 5.1.2 on 2024-11-04 03:24

import okp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0002_okpforumsection_show_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='banner',
            field=okp.fields.okpImageField(blank=True, null=True, upload_to='forums/sections/banners', validators=[okp.fields.okpImageSizeValidator], verbose_name='Banner'),
        ),
    ]
