# Generated by Django 5.1.2 on 2024-11-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0003_okpforumsection_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='banner_height',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Banner Height'),
        ),
    ]
