# Generated by Django 5.1.2 on 2024-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_okpforumcategory_sortby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
