# Generated by Django 5.0.7 on 2024-07-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0003_alter_okpforummessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumcategory',
            name='list_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='List of Topics'),
        ),
        migrations.AlterField(
            model_name='okpforumcategory',
            name='total_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AlterField(
            model_name='okpforumcategory',
            name='total_topics',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Topics'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='list_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='List of Topics'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='total_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='total_topics',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Topics'),
        ),
        migrations.AlterField(
            model_name='okpforumtopic',
            name='total_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Messages'),
        ),
    ]
