# Generated by Django 5.1.2 on 2024-11-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okp_forums', '0004_okpforumsection_banner_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='basis',
            field=models.CharField(choices=[('100', '100% (4/4)'), ('75', '75% (3/4)'), ('66', '66% (2/3)'), ('50', '50% (2/4)'), ('33', '33% (1/3)'), ('25', '25% (1/4)')], default='25', max_length=4, verbose_name='Basis'),
        ),
    ]
