# Generated by Django 5.0.7 on 2024-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0004_alter_okpforumcategory_list_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
