# Generated by Django 5.0.7 on 2024-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0005_alter_okpforumcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumtopic',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
