# Generated by Django 5.0.7 on 2024-08-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0006_alter_okpforumtopic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='okpforums.okpforumsection', verbose_name='Section'),
        ),
    ]
