# Generated by Django 5.1.2 on 2024-10-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_okpforummessage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumcategory',
            options={'ordering': ['game', models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'ordering': ['game', 'category', models.OrderBy(models.F('sortby'), nulls_last=True), 'created_at'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='okpforumtopic',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='okpforummessage',
            name='name',
        ),
    ]
