# Generated by Django 5.0.7 on 2024-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0007_okpforumsection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumtopic',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
