# Generated by Django 5.1.2 on 2024-10-29 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_okpforumcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumtopic',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_topic', to='forums.okpforummessage', verbose_name='Last Message'),
        ),
    ]
