# Generated by Django 5.1.2 on 2024-10-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_okpforumtopic_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpforumsection',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_section', to='forums.okpforummessage', verbose_name='Last Message'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='last_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_topic_section', to='forums.okpforumtopic', verbose_name='Last Topic'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='total_messages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='total_topics',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Topics'),
        ),
        migrations.AddField(
            model_name='okpforumtopic',
            name='total_messages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Messages'),
        ),
    ]
