# Generated by Django 5.1.2 on 2024-10-30 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_okpforumsection_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforummessage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forums.okpforumsection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='okpforummessage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forums.okpforumtopic', verbose_name='Topic'),
        ),
    ]
