# Generated by Django 5.0.7 on 2024-08-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0009_alter_okpforummessage_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okpforumtopic',
            name='total_messages',
        ),
    ]
