# Generated by Django 5.0.7 on 2024-08-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0010_remove_okpforumtopic_total_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumcategory',
            options={'ordering': ['order_by', 'pk'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='okpforummessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'ordering': ['order_by', 'pk'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='okpforumtopic',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='okpforumcategory',
            name='order_by',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='order_by',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordering'),
        ),
    ]
