# Generated by Django 5.0.7 on 2024-08-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0011_alter_okpforumcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okpforumcategory',
            options={'ordering': ['forum', 'order_by', 'pk'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='okpforumsection',
            options={'ordering': ['forum', 'category', 'order_by', 'pk'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='okpforumsection',
            name='total_messages',
        ),
        migrations.RemoveField(
            model_name='okpforumsection',
            name='total_topics',
        ),
        migrations.AddField(
            model_name='okpforumsection',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='forums/sections/covers/', verbose_name='Cover'),
        ),
    ]
