# Generated by Django 5.0.7 on 2024-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpforums', '0012_alter_okpforumcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpforumcategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='okpforumsection',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
