import type { Metadata } from "next";
import { fontOpenSans } from "@/app/_lib/fonts";
import "@/app/_assets/styles/core.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr">
      <body className={fontOpenSans.className}>
        <header className="okp-core-header">
          <div>logo</div>
          <div>links</div>
          <div>user</div>
        </header>
        <div className="okp-core-content">
          <navbar className="okp-core-leftbar">
            <div>leftbar</div>
          </navbar>
          <main className="okp-core-main">
            {children}
          </main>
          <navbar className="okp-core-righbar">
            <div>righbar</div>
          </navbar>
        </div>
      </body>
    </html>
  );
}
