# Generated by Django 5.1.3 on 2024-11-23 01:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixa_pages', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([], block_lookup={}, default='test'),
            preserve_default=False,
        ),
    ]
