# Generated by Django 5.1.3 on 2024-11-23 01:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixa_pages', '0003_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_en',
            field=wagtail.fields.StreamField([], block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_fr',
            field=wagtail.fields.StreamField([], block_lookup={}, null=True),
        ),
    ]
