# Generated by Django 5.1.3 on 2024-11-23 02:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixa_pages', '0004_homepage_content_en_homepage_content_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_en',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_fr',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
    ]
