# Generated by Django 4.2.7 on 2023-11-11 16:59

from django.db import migrations, models
import okp.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[okp.users.validators.okpValidatorsAvatar], verbose_name='Avatar'),
        ),
    ]
