import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Ma page ;)",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <header className="okp-container">
        <h1>Oykus</h1>
      </header>
    </>
  );
}
