# Generated by Django 5.1.3 on 2024-11-30 20:58

import django.contrib.auth.validators
import okp.fields
import okp.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OkpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('playername', models.CharField(blank=True, max_length=255, verbose_name='Playername')),
                ('abbr', models.CharField(blank=True, max_length=3, verbose_name='Abbreviation')),
                ('avatar', okp.fields.okpImageField(blank=True, null=True, upload_to='users/avatars', validators=[okp.fields.okpImageSizeValidator], verbose_name='Avatar')),
                ('cover', okp.fields.okpImageField(blank=True, null=True, upload_to='users/covers', validators=[okp.fields.okpImageSizeValidator], verbose_name='Cover')),
                ('can_create_game', models.BooleanField(default=True, help_text='Whether the user can create games.', verbose_name='Can Create Game')),
                ('can_create_character', models.BooleanField(default=True, help_text='Whether the user can create characters.', verbose_name='Can Create Character')),
                ('max_games', models.PositiveSmallIntegerField(default=2, help_text='Maximum number of games a user can create.', verbose_name='Max Games')),
                ('max_characters', models.PositiveSmallIntegerField(default=10, help_text='Maximum number of characters a user can create.', verbose_name='Max Characters')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', okp.users.models.OkpUserManager()),
            ],
        ),
    ]
