# Generated by Django 5.0.7 on 2024-07-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpuserprofile',
            name='list_unread_topics',
            field=models.JSONField(default=list, verbose_name='List of Unread Topics'),
        ),
    ]
