# Generated by Django 5.0.7 on 2024-07-20 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpusers', '0002_okpuserprofile_list_unread_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='okpRat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat', models.CharField(max_length=40, unique=True, verbose_name='Rat')),
                ('agent', models.CharField(max_length=120, verbose_name='Agent')),
                ('expired_at', models.DateTimeField(verbose_name='Expired At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rat',
                'verbose_name_plural': 'Rats',
            },
        ),
    ]
