# Generated by Django 5.0.7 on 2024-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpusers', '0003_okprat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okprat',
            name='agent',
            field=models.CharField(max_length=250, verbose_name='Agent'),
        ),
    ]
