# Generated by Django 5.0.7 on 2024-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpusers', '0004_alter_okprat_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpuserprofile',
            name='list_unread_topics',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='List of Unread Topics'),
        ),
    ]
