# Generated by Django 5.0.7 on 2024-08-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okpusers', '0005_alter_okpuserprofile_list_unread_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='okpuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
